"""
Lista com textos das missões
"""

missoes = ["Nome funcao 1",
           "Nome funcao 2",
           "Nome funcao 3",
           "Nome funcao 4",
           "Nome funcao 5",
           "Nome funcao 6",
           "Nome funcao 7",
           "Nome funcao 8",
           "Nome funcao 9",
           "Nome funcao 10",
           "Nome funcao 11",
           "Nome funcao 12",
           "Nome funcao 13",
           "Nome funcao 14",
           "Nome funcao 15",
           "Nome funcao 16",
           "Nome funcao 17",
           "Nome funcao 18",
           "Nome funcao 19",
           "Nome funcao 20",
           "Nome funcao 21",
           "Nome funcao 22",
           "Nome funcao 23",
           "Nome funcao 24",
           "Nome funcao 25",
           "Nome funcao 26",
           "Nome funcao 27",
           "Nome funcao 28",
           "Nome funcao 29",
           "Nome funcao 30",
           "Nome funcao 31",
           "Nome funcao 32",
           "Nome funcao 33",
           "Nome funcao 34",
           "Nome funcao 35",
           "Nome funcao 36",
           "Nome funcao 37",
           "Nome funcao 38",
           "Nome funcao 39",
           "Nome funcao 40",
           "Nome funcao 41",
           "Nome funcao 42",
           "Nome funcao 43",
           "Nome funcao 44",
           "Nome funcao 45",
           "Nome funcao 46",
           ]
